- name: Stop filebeat service
  ansible.builtin.systemd:
    state: stopped
    name: filebeat

- name: Delete factory filebeat zeek.yml config
  ansible.builtin.file:
    path: /etc/filebeat/modules.d/zeek.yml
    state: absent

- name: Create zeek.yml config
  ansible.builtin.copy:
    dest: /etc/filebeat/modules.d/zeek.yml
    content: |
      # Module: zeek
      # Docs: https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-module-zeek.html

      - module: zeek
        capture_loss:
          enabled: true
        connection:
          var.paths: ["/opt/zeek/logs/current/conn.log"]
          enabled: true
        dce_rpc:
          var.paths: ["/opt/zeek/logs/current/dce_rpc.log"]
          enabled: true
        dhcp:
          var.paths: ["/opt/zeek/logs/current/dhcp.log"] 
          enabled: true
        dnp3:
          var.paths: ["/opt/zeek/logs/current/dnp3.log"] 
          enabled: true
        dns:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/dns.log"]
        dpd:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/dpd.log"]
        files:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/files.log"]
        ftp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ftp.log"]
        http:
          var.paths: ["/opt/zeek/logs/current/http.log"]
          enabled: true
        intel:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/intel.log"]
        irc:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/irc.log"]
        kerberos:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/kerberos.log"]
        modbus:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/modbus.log"]
        mysql:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/mysql.log"]
        notice:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/notice.log"]
        ntp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ntp.log"]
        ntlm:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ntlm.log"]
        ocsp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ocsp.log"]
        pe:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/pe.log"]
        radius:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/radius.log"]
        rdp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/rdp.log"]
        rfb:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/rfb.log"]
        signature:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/signature.log"]
        sip:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/sip.log"]
        smb_cmd:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/smb_cmd.log"]
        smb_files:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/smb_files.log"]
        smb_mapping:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/smb_mapping.log"]
        smtp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/smtp.log"]
        snmp:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/snmp.log"]
        socks:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/socks.log"]
        ssh:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ssh.log"]
        ssl:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/ssl.log"]
        stats:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/stats.log"]
        syslog:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/syslog.log"]
        traceroute:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/traceroute.log"]
        tunnel:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/tunnel.log"]
        weird:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/weird.log"]
        x509:
          enabled: true
          var.paths: ["/opt/zeek/logs/current/x509.log"]

          # Set custom paths for the log files. If left empty,
          # Filebeat will choose the paths depending on your OS.
          #var.paths:

- name: Start filebeat service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: filebeat