---
- name: Create user list
  hosts: localhost
  gather_facts: false
  vars:
    vault_pass_path: "./.vault_pass"
    inventory_path: "./ansible/inventory/production/inventory.yml"
    playbook_path: "./ansible/playbook/production/playbook-get-random-users.yml"
    users_file_path: "./files/users.txt"
  tasks:
    - name: Check if users file exists
      stat:
        path: "{{ users_file_path }}"
      register: users_file

    - name: Prompt to generate new users file if it exists
      block:
        - name: Prompt to generate new users file
          pause:
            prompt: "Do you wish to generate a new users file?"
            echo: true
          register: generate_new_file

        - name: Remove existing users file
          file:
            path: "{{ users_file_path }}"
            state: absent
          when: generate_new_file.user_input == 'Yes'
      when: users_file.stat.exists

    - name: Generate new users file if it doesn't exist
      block:
        - name: Run playbook to get random users
          ansible.builtin.include_role:
            name: roles/windows/get-random-users
          vars:
            vault_password_file: "{{ vault_pass_path }}"
            inventory: "{{ inventory_path }}"
            playbook: "{{ playbook_path }}"
            output_file: "{{ users_file_path }}"
          become: true
          become_method: su

        - name: Remove non-printable characters from users file
          replace:
            path: "{{ users_file_path }}"
            regexp: '[^[:print:]]'
            replace: ''

        - name: Remove blank lines from users file
          replace:
            path: "{{ users_file_path }}"
            regexp: '^\s*$\n'
            replace: ''

        - name: Remove first line from users file
          lineinfile:
            path: "{{ users_file_path }}"
            state: absent
            line: "{{ item }}"
          with_first_found:
            - "{{ lookup('file', users_file_path) | split('\n') | list | first }}"
          when: item is defined

        - name: Remove whitespace from users file
          replace:
            path: "{{ users_file_path }}"
            regexp: '\s+'
            replace: ''
      when: not users_file.stat.exists
