---
- name: Check if VSCode for Windows exists
  task:
    ansible.builtin.stat:
      path: "{{ windows_agent_dir }}/{{ windows_agent_file }}"
  register: file_exists
  ignore_errors: true

- name: Download VSCode for Windows
  get_url:
    url: "{{ windows_agent_url }}"
    dest: "{{ windows_agent_dir }}/{{ windows_agent_file }}"