---
- name: Check if VSCode for Windows exists
  task:
    ansible.builtin.stat:
      path: "../../roles/windows/install-python311/files/python311.exe"
  register: file_exists
  ignore_errors: true

- name: Download VSCode for Windows
  get_url:
    url: "{{ windows_agent_url }}"
    dest: "../../roles/windows/install-python311/files/python311.exe"