---
- name: Clean up the generated user file
  replace:
    path: "{{ users_file_path }}"
    regexp: '[^\x20-\x7E]'
    replace: ''
  with_items:
    - '^\n'
    - '^ \n'
  when: users_file.stat.exists

- name: Remove first line from users file
  lineinfile:
    path: "{{ users_file_path }}"
    state: absent
    line: "{{ lookup('file', users_file_path) | regex_replace('^.*?\n', '') }}"
  when: users_file.stat.exists

- name: Remove whitespace from users file
  replace:
    path: "{{ users_file_path }}"
    regexp: '\s+'
    replace: ''
  when: users_file.stat.exists
