---
- name: Test playbook
  hosts: localhost
  gather_facts: no
  vars_files:
    - cobra.vault.yml
  tasks:
    - name: Debug vault variables
      debug:
        var: item.value
      loop: "{{ lookup('dict', vars) }}"
