- name: Copy CA certificate to host
  ansible.windows.win_copy:
    src: ./ca.crt
    dest: 'C:\ca.crt'

- name: Install CA certificate in Trusted Root CA Store
  ansible.windows.win_command: certutil -addstore "Root" "C:\ca.crt"

- name: Clean up install files
  ansible.windows.win_file:
    path: C:\ca.crt
    state: absent