- name: Copy CA certificate to host
  ansible.windows.win_copy:
    src: ./ca.crt
    dest: 'C:\ca.crt'

- name: Install CA certificate in Trusted Root CA Store
  ansible.windows.win_certificate_store:
    path: C:\ca.crt
    store_name: Root
    state: present

- name: Clean up install files
  ansible.windows.win_file:
    path: C:\ca.crt
    state: absent
