---
- name: Ensure VSCode install directory exists
  ansible.windows.win_file:
    path: "C:\\Tools\\VSCode"
    state: directory


- name: Download VS Code installer
  ansible.windows.win_get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
    dest: "C:\\Tools\\VSCode\\vscode-latest.exe"
    validate_certs: no
  become: yes
  become_method: runas
  become_user: "{{ admin_username }}"

- name: Install VS Code latest for Windows
  ansible.windows.win_shell: "C:\\Tools\\VSCode\vscode-latest.exe /verysilent /mergetasks=!runcode"


- name: Install Chocolatey if not already installed
  ansible.windows.win_shell: |
    if (!(Test-Path 'C:\ProgramData\chocolatey\bin\choco.exe')) {
      Set-ExecutionPolicy Bypass -Scope Process -Force;
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    }

- name: Install VS Code extensions
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    - ms-python.python
    - donjayamanne.python-extension-pack
    - ms-toolsai.jupyter
