- name: Install community.general collection
  hosts: localhost
  gather_facts: false
  vars:
    galaxy_collections:
      - name: community.general
      - name: ansible.windows
      - name: ansible.posix
  roles:
    - role: common/tasks/tasks-ansible-collections.yml

- name: Download Required Files to Localhost
  hosts: localhost
  vars:
    windows_agent_file: "vscode-latest.exe"
    windows_agent_dir: "roles/windows/vscode/files"
    windows_agent_name: "vscode-latest"
    windows_agent_url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
  tasks:  
    - ansible.builtin.import_tasks:
        file: roles/common/tasks/tasks-download-vscode.yml

- name: Install VS Code on Windows target
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    vs_code_url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
  roles:
    - roles/windows/vscode
