---
- name: Verify if User File exists
  hosts: localhost
  gather_facts: false
  vars:
    vault_pass_path: "./.vault_pass"
    inventory_path: "{{ project_root }}inventory/production/inventory.yml"
    playbook_path: "{{ project_root }}playbook/production/playbook-get-random-users.yml"
    users_file_path: "./files/users.txt"
  tasks:
    - name: Import tasks
      ansible.builtin.import_tasks: 
        file: "../../roles/common/tasks/task-verify-user-exists.yml"

- name: Get 30 random users and reset password to ComtechAzure123!
  hosts: dc1
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    users_file_path: "./files/users.txt"
  roles:
    - role: ../../roles/windows/get-random-users

- name: Update Inventory List
  hosts: localhost
  gather_facts: false
  vars:
    vault_pass_path: "./.vault_pass"
    inventory_path: "{{ project_root }}inventory/production/inventory.yml"
    playbook_path: "{{ project_root }}playbook/production/playbook-get-random-users.yml"
    users_file_path: "./files/users.txt"
  tasks:
    - name: Update the Inventory
      ansible.builtin.import_tasks:
        - file: "../../roles/common/tasks/task-update-inventory.yml" 