---
- name: Install Python packages with pip
  hosts: localhost
  become: true
  tasks:
    - name: Install Python packages
      pip:
        name:
          - package1
          - package2
          - package3
        state: present
