---
- name: Check if collections are already installed
  command: ansible-galaxy collection list
  register: galaxy_list
  changed_when: false

- name: Install required collections
  ansible.builtin.ansible_galaxy:
    name: "{{ item.name }}"
    state: present
  loop: "{{ galaxy_collections }}"
  when: item.name not in galaxy_list.stdout
