---
- name: Check if collections are already installed
  command: ansible-galaxy collection list
  register: galaxy_list
  changed_when: false

- name: Install collections if not already present
  include_role:
    name: ansible-galaxy
  when: item not in galaxy_list.stdout
  loop: "{{ galaxy_collections }}"

- name: Install collections
  include_role:
    name: ansible-galaxy
  when: galaxy_collections | selectattr('name', 'notin', galaxy_list.stdout_lines) | list | count > 0

- name: Check if collection is already installed
  command: ansible-galaxy collection list
  register: galaxy_list
  changed_when: false
