---
- name: Check if collection is already installed
  command: ansible-galaxy collection list
  register: galaxy_list
  changed_when: false

- name: Install required collections
  command: ansible-galaxy collection install {{ item.name }}
  register: install_result
  when: "'{{ item.name }}' not in galaxy_list.stdout"
  loop: "{{ galaxy_collections }}"

- debug:
    msg: "The following collections were installed: {{ galaxy_collections }}"
  when: install_result|changed