---
- name: Check if VSCode for Windows exists
  ansible.builtin.stat:
    path: "{{ windows_agent_dir }}/{{ windows_agent_file }}"
  register: windows_file_exists
  ignore_errors: true

- name: Download VSCode for Windows
  get_url:
    url: "{{ windows_agent_url }}"
    dest: "{{ windows_agent_dir }}/{{ windows_agent_file }}"
  when: not windows_file_exists