- name: Create folder to host covenant
  ansible.builtin.file:
    path: {{ covenant_basepath }}
    owner: red
    group: red
    state: directory

- name: Create Bash Launcher Script
  copy:
    dest: "{{covenant_basepath}}/covenant.sh"
    mode: 0755
    content: |
      #!/bin/bash
      cd {{ covenant_basepath }}
      git clone --recurse-submodules https://github.com/cobbr/Covenant
      cd {{ covenant_fullpath }}
      docker build -t covenant .
      docker run -it -p 7443:7443 -p 80:80 -p 443:443 --name covenant -v </absolute/path/to/Covenant/Covenant/Data>:/app/Data covenant


- name: Execute covenant script
  ansible.builtin.shell: cd {{ covenant_basepath }} && ./covenant.sh