- name: Copy Python311 to target
  win_copy:
    src: "{{ role_path }}/files/{{ python311_exe }}"
    dest: "C:\\{{ python311_exe }}"

- name: Install Python311
  win_shell: C:\{{ python311_exe }} /quiet InstallAllUsers=1 TargetDir=C:\Tools\Python311 PrependPath=1

- name: Set Python311 path
  win_environment:
    name: PATH
    value: C:\Tools\Python311;C:\Tools\Python311\Scripts
    state: present
    level: machine
  when: install_path == "true"

- name: Install requests and pyyaml with pip3
  ansible.builtin.win_pip:
    name:
      - requests
      - pyyaml
      - thehive4py
      - python-magic-dev
      - libmagic
      - elasticsearch7
      - kubernetes
      - keycloak
    state: latest
    executable: C:\Tools\Python311\Scripts\pip3.exe
