- name: Copy Python311 to target
  win_copy:
    src: "{{ role_path }}/files/{{ python311_exe }}"
    dest: "C:\\{{ python311_exe }}"

- name: Install Python311
  ansible.windows.shell: |
    C:\\{{ python311_exe }} /quiet InstallAllUsers=1 TargetDir=C:\\Tools\Python311" PrependPath=1
