[datacenter.dc1]
ansible_host = "172.17.40.4"

[datacenter.dc2]
ansible_host = "172.17.40.5"

[subnet.subnet1]
[user]
for i in range(1, 11):
  [user.user{i}]
  ansible_host = "172.17.10.${i+3}"
  ansible_user = "admin"
  ansible_password = "password"

[subnet.subnet2]
[user]
for i in range(11, 21):
  [user.user{i}]
  ansible_host = "172.17.10.${i-7}"
  ansible_user = "admin"
  ansible_password = "password"

[subnet.subnet3]
[user]
for i in range(21, 31):
  [user.user{i}]
  ansible_host = "172.17.10.${i-17}"
  ansible_user = "admin"
  ansible_password = "password"

[gns3.host1]
ansible_host = "10.255.255.100"

[sensor.host1]
ansible_host = "172.17.60.50"

[operators.blue]
for i in range(1, 16):
  [operators.blue.blue{i}]
  ansible_host = "172.17.60.${i+100}"
