- name: Download and install Python311 on Windows
  hosts: " {{ $targets }} "
  gather_facts: false
  vars:
    python311_url: "https://www.python.org/ftp/python/3.11.1/python-3.11.1-amd64.exe"
    python311_exe: "python311.exe"
    ansible_user: "{{ den_user }}"
    ansible_password: "{{ den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  - name: Check if file exists
    stat:
      path: "{{ role_path }}/files/python-3.11-amd64.exe"
    register: python_register
  - name: Download Python311
    get_url:
      url: "https://www.python.org/ftp/python/3.11/python-3.11-amd64.exe"
      dest: "{{ role_path }}/files/python-3.11-amd64.exe"
    when: not register_name.stat.exists

  roles:
    - role: roles/windows/install-python311