---
- name: Add CA certificate to trust store
  hosts: datacenter subnet1 subnet2 subnet3 operator
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
  roles:
    - role: roles/windows/root-cert