- name: Login random users to client workstations
  hosts: user1 user2 user3 user4 user5 user6 user7 user8 user9 user10 user11 user12 user13 user14 user15 user16 user17 user18 user19 user20  user21 user22 user23 user24 user25 user26 user27 user28 user29 user30
  gather_facts: no
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ den_user }}"
    ansible_password: "{{ den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
    username: "{{ uname }}"
  roles:
    - role: roles/windows/gpupdate
    - role: roles/windows/login-random-users