---
- name: Login random users to client workstations
  hosts: subnet1,subnet2,subnet3
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    username: "{{ uname }}"
  ansible.builtin.import_roles:
    - file: "./roles/windows/gpupdate"
  ansible.builtin.import_roles:
    - file: "./roles/windows/login-random-users"