- name: Install VS Code on Windows target
  hosts: " {{ target_host }} "
  gather_facts: no
  become: true
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    vs_code_url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
  roles:
    - roles/windows/vscode
  tasks:
    - name: Download VS Code latest for Windows
      ansible.builtin.get_url:
        url: "{{ vs_code_url }}"
        dest: roles/windows/vscode/files/vscode-latest.exe
