---
- name: Configure Windows system for log ingestion (Winlogbeat/sysmon64)
  hosts: datacenter,subnet1,subnet2,subnet3
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
  roles:
    - role: roles/windows/winlogbeat