---
- name: Install community.general collection
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.import_tasks: ./common/tasks/task-ansible-collection.yml

- name: Download Required Files to Localhost
  hosts: localhost
  vars:
    windows_agent_file: "elastic-agent-7.17.4-windows-x86_64.zip"
    windows_agent_dir: "roles/windows/elastic-agent/files"
    windows_agent_name: "elastic-agent-7.17.4-windows-x86_64"
    windows_agent_exe: "elastic-agent.exe"
    windows_agent_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/{{ windows_agent_file }}"
    linux_agent_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.4-linux-x86_64.tar.gz"
    linux_agent_name: "elastic-agent-7.17.4-linux-x86_64"
    linux_agent_dir: "roles/linux/elastic-agent/files"
    linux_agent_file: "elastic-agent-7.17.4-linux-x86_64.zip"
  tasks:  
  - name: Check if Elastic Agent for Windows exists
    ansible.windows.win_stat:
      path: "{{ windows_agent_dir }}/{{ windows_agent_file }}"
    register: file_exists
    ignore_errors: true

  - name: Unarchive the downloaded Elastic
    ansible.builtin.unarchive:
      src: "{{ windows_agent_url }}"
      dest: "{{ windows_agent_dir }}"
      remote_src: yes
      creates: "{{ windows_agent_dir }}/{{ windows_agent_name }}/{{ windows_agent_exe }}"


  # - name: Verify Elastic Agent for Windows exists
  #   assert:
  #     that:
  #       - file_exists.stat.exists
  #     msg: "Elastic Agent for Windows could not be downloaded or does not exist"

- name: "Configure Windows system for log ingestion (Elastic Agent)"
  hosts: "{{ elastic_targets }}"
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    ansible_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/windows/root-cert
    - role: roles/windows/elastic-agent
