---
- name: Verify if User File exists
  hosts: localhost
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    vault_pass_path: "./.vault_pass"
    inventory_path: "./ansible/inventory/production/inventory.yml"
    playbook_path: "./ansible/playbook/production/playbook-get-random-users.yml"
    users_file_path: "./files/users.txt"
  tasks:
    - ansible.builtin.import_tasks: 
      -file: ./common/tasks/task-verify-user-exists.yml

- name: Get 30 random users and reset password to ComtechAzure123!
  hosts: dc1
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/windows/get-random-users
  tasks:
    - ansible.builtin.import_tasks:
      - file: ./common/tasks/tasks-update-inventory.yml 