---
- name: Refresh Group Policy
  hosts: datacenter subnet1 subnet2 subnet3
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    ansible_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  tasks:
    - name: Refresh Group Policy
      ansible.windows.win_command: gpupdate /force /boot
