---
- name: Login random users to client workstations
  hosts: user1 user2 user3 user4 user5 user6 user7 user8 user9 user10 user11 user12 user13 user14 user15 user16 user17 user18 user19 user20  user21 user22 user23 user24 user25 user26 user27 user28 user29 user30
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    username: "{{ uname }}"
  roles:
    - role: "./roles/windows/gpupdate"
    - role: "./roles/windows/login-random-users"