- name: Configure Windows system for log ingestion (Elastic Agent)
  hosts: datacenter subnet1 subnet2 subnet3
  gather_facts: no
  vars:
    ansible_user: "{{ den_user }}"
    ansible_password: "{{ den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/windows/root-cert
    - role: roles/windows/elastic-agent