# - name: Kickoff Playbook
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - name: Starting Elastic Agent Install
#       ansible.builtin.import_playbook: ./playbook-elastic-agent.yml

#     - name: Starting Python Install
#       ansible.builtin.import_playbook: ./playbook-install-python311.yml

#     - name: Starting Tap Collector
#       ansible.builtin.import_playbook: ./playbook-tap-collector.yml

#     - name: Starting VSCode Setup
#       ansible.builtin.import_playbook: ./playbook-install-vscode.yml

#     - name: Starting Random Users
#       ansible.builtin.import_playbook: ./playbook-login-random-users.yml
---
- name: Kickoff Playbook
  gather_facts: no
  tasks:
    - name: Starting Elastic Agent Install
      include: ./playbook-elastic-agent.yml

    - name: Starting Python Install
      include: ./playbook-install-python311.yml

    - name: Starting Tap Collector
      include: ./playbook-tap-collector.yml

    - name: Starting VSCode Setup
      include: ./playbook-install-vscode.yml

    - name: Starting Random Users
      include: ./playbook-login-random-users.yml

