---
- name: Install community.general collection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if collection is already installed
      command: ansible-galaxy collection list
      register: galaxy_list
      changed_when: false

    - name: Install ansible-windows collections
      include_role:
        name: ansible-galaxy
      vars:
        galaxy_install_collections:
          - ansible.windows
      when: "'ansible.windows' not in galaxy_list.stdout"

    - name: Install ansible-windows collections
      include_role:
        name: ansible-galaxy
      vars:
        galaxy_install_collections:
          - ansible.posix
      when: "'ansible.posix' not in galaxy_list.stdout"

- name: Download Required Files to Localhost
  hosts: localhost
  vars:
    windows_agent_file: "vscode-latest.exe"
    windows_agent_dir: "roles/windows/vscode/files"
    windows_agent_name: "vscode-latest"
    windows_agent_url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
  tasks:  
  - name: Check if Elastic Agent for Windows exists
    ansible.windows.win_stat:
      path: "{{ windows_agent_dir }}/{{ windows_agent_file }}"
    register: file_exists
    ignore_errors: true

  - name: Download VSCode for Windows
    get_url:
      url: "{{ windows_agent_url }}"
      dest: "{{ windows_agent_dir }}/{{ windows_agent_file }}"

- name: Install VS Code on Windows target
  hosts: "{{ target_host }}"
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    log_file_path: "./ansible-errors.log"
    timeout: 60
    vs_code_url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
  roles:
    - roles/windows/vscode
