---
- name: Download Python to localhost
  host: localhost
  vars:
    python_windows_url: https://www.python.org/ftp/python/3.11.2/python-3.11.2-amd64.exe
    python_windows_dest: ansible/roles/windows/install-python311/files/python311.exe
    python_linux_url: https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
    python_linux_dest: ansible/roles/linux/install-python311/files/python311.tar.gz
  task:
  - name: Download Python for Windows
    get_url:
      url: "{{ python_windows_url }}"
      dest: "ansible/roles/windows/install-python311/files/{{ python_windows_file }}"
    when: not (ansible_check_mode | bool) and not (file_exists.stat.exists)
    vars:
      file_exists: "{{ lookup('file', python_windows_file) }}"

  - name: Download Python for Linux
    get_url:
      url: "{{ python_linux_url }}"
      dest: "ansible/roles/linux/install-python311/files/{{ python_linux_file }}"
    when: not (ansible_check_mode | bool) and not (file_exists.stat.exists)
    vars:
      file_exists: "{{ lookup('file', python_linux_file) }}"

  - name: Verify Python for Windows exists
    assert:
      that:
        - file_exists.stat.exists
      quiet: yes
    vars:
      file_exists: "{{ lookup('file', python_windows_file) }}"

  - name: Verify Python for Linux exists
    assert:
      that:
        - file_exists.stat.exists
      quiet: yes
    vars:
      file_exists: "{{ lookup('file', python_linux_file) }}"

- name: "Install Python311 on Windows"
  hosts: "{{ python_targets }}"
  gather_facts: false
  vars_files:
    - cobra.vault
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 1000
    ansible_winrm_read_timeout_sec: 3200
    anisble_winrm_connection_timeout_sec: 2000
    reconnection_retries: 10
    timeout: 60
  roles:
    - role: roles/windows/install-python311
