---
- name: Refresh Group Policy
  hosts: datacenter subnet1 subnet2 subnet3
  gather_facts: false
  vars:
    ansible_user: "{{ vault_den_user }}"
    ansible_password: "{{ vault_den_user_password }}"
  tasks:
    - name: Refresh Group Policy
      ansible.windows.win_command: gpupdate /force /boot
