---
- name: Install packages
  hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - unzip
          - pyyaml
          - jq
        state: present
  vars:
    ansible_become_password: "{{ vault_linux_user_password }}"