---
- name: Update and Upgrade APT Packages
  hosts: localhost
  become: true
  var_files:
    - ../vault/cobraden.yml
  
  tasks:
    - name: Run APT Update
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Run APT Upgrade
      ansibel.builtin.apt:
        upgrade: dist

    - name: Run APT Autoremove
      ansible.builtin.apt:
        autoremove: yes